version: "3.4"
networks:
  proxynetwork:
    external: true
services:
  www:
    image: koromerzhin/nodejs:15.0.1-sveltejs
    volumes:
      - ${PWD}/apps:/app
    networks:
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.www-sveltejs.rule=Host(`sveltejs.lxc`, `www.sveltejs.lxc`)"
        - "traefik.http.middlewares.wwwredirectregex.redirectregex.regex=^http://sveltejs.lxc/(.*)"
        - "traefik.http.middlewares.wwwredirectregex.redirectregex.replacement=http://www.sveltejs.lxc/$${1}"
        - "traefik.http.routers.www-sveltejs.entrypoints=web"
        - "traefik.http.services.www-sveltejs.loadbalancer.server.port=8080"
