version: "3.4"
networks:
  proxynetwork:
    external: true
services:
  www:
    image: koromerzhin/nodejs:3.29.4-sveltejs
    volumes:
      - ${PWD}/apps:/app
    networks:
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sveltejs.rule=Host(`sveltejs.traefik.me`)"
        - "traefik.http.routers.sveltejs-tls.tls.domains[0].main=sveltejs.traefik.me"
        - "traefik.http.routers.sveltejs-tls.tls.domains[0].sans=sveltejs-*.traefik.me"
        - "traefik.http.services.www-sveltejs.loadbalancer.server.port=8080"
