version: "3.4"
networks:
  proxylampy:
    external: true
services:
  www:
    image: node:15.14.0
    working_dir: /app
    command: >
      sh -c "npm install && npm run start"
    volumes:
      - ${PWD}/apps:/app
    networks:
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sveltejs.rule=Host(`sveltejs.traefik.me`)"
        - "traefik.http.routers.sveltejs-tls.tls.domains[0].main=sveltejs.traefik.me"
        - "traefik.http.routers.sveltejs.tls=true"
        - "traefik.http.services.www-sveltejs.loadbalancer.server.port=8080"
